### ISSUE TITLE
Grammar cannot handle types in quotes for parameters

### ISSUE THREAD

**Issue by MnemonicWME** [ezequielgandolfi/openedge-zext#12]
Class names enclosed in quotes in parameter definition, such as:

DEFINE INPUT PARAMETER obj AS CLASS "Progress.Lang.Object" NO-UNDO.

seem to confuse the syntax highlighting and all the code after the starting quote is considered a string.

**Comment by ezequielgandolfi** [comment]
Released in v0.3.0
