### ISSUE TITLE
Capitalize basic commands

### ISSUE THREAD

**Issue by andresapao** [ezequielgandolfi/openedge-zext#28]
Commands like "for each", "def var" should be capitalized

**Comment by aastarius** [comment]
> Commands like "for each", "def var" should be capitalized

Only if it's made totally optional as doing that in my working environment will get me slapped ...

**Comment by andresapao** [comment]
Do you prefer an option at settings?

**Comment by aastarius** [comment]
Yeah, a specific option would be best though does actually look like its already on the todo list.

**Comment by ezequielgandolfi** [comment]
Version 0.6.0 will be release soon with new commands to change case from keywords (upper/lower case)

**Comment by ezequielgandolfi** [comment]
v0.6.0 released
