### ISSUE TITLE
openedge-zext.json not used parameters ?

### ISSUE THREAD

**Issue by DadMl** [ezequielgandolfi/openedge-zext#29]
Hi,

I'm not able to get the parameters for this .json file openedge-zext.json taken into framework.

I'm able to run openedge , I tried to overwrite dlcpath , parametersfiles, and ini file,
but the values are still not defined if adding some displays into ablrun.js procedure.

Is the location is OK , should be in the workspace ?.

Note : I used the .json from the repository.

**Comment by DadMl** [comment]
i'm confuse , it was bad name used for file,

need to be .openedge-zext.json

with a dot at first character.

**Comment by ezequielgandolfi** [comment]
Hi. The dot at first position is like a pattern for "hidden" files. You can see the same pattern in the default vscode settings folder (\.vscode).
I will create a setting to choose the config file.

**Comment by DadMl** [comment]
Hi thank you

Not sure it will be necessary to have a such option, it's a mistake i done.

But 2 other options are missing,

One option is to add some session-parameter string just after the file to run/compile.
Actually i added them directly in ablrun.js, concatenated after filename,this is because the framework launched after ,needs to use some specific session parameters.

An other option should be to setup a program name to be launch at the end of pre-launch.p,
Typically the one i hardcoded is to create a specific connection, initialization of our frameworks.
For now i have added in the pre-launch.p program.

Thank.
Le 11 nov. 2019, à 23:05, Ezequiel Gandolfi <notifications@github.com<mailto:notifications@github.com>> a écrit:

Hi. The dot at first position is like a pattern for "hidden" files. You can see the same pattern in the default vscode settings folder (.vscode).
I will create a setting to choose the config file.
