### ISSUE TITLE
VS Code autocomplete does not respect progress identifiers

### ISSUE THREAD

**Issue by jonathanmcelroy** [ezequielgandolfi/openedge-zext#31]
The codebase I'm working on has variables with dashes "-" in them. VS Code only considers alphanumeric characters and underscores in an identifier, so autocomplete will not complete the full variable. Progress allows identifiers with these special characters: "_$#%&-".

**Comment by ezequielgandolfi** [comment]
Hi. The extension has autocomplete for tables/buffers, fields and procedures. The variables are suggested by VSCode only, not by the extension.
I have a issue (#9) to suggest variables.

**Comment by ezequielgandolfi** [comment]
v1.0.0 released with autocomplete for global, local and parameters identifiers
